/**
 * AUTO-GENERATED by `composer sync:api-types` (php artisan typescript:transform).
 * Empty until the backend lane ships code — do NOT hand-edit.
 * Until then, the contract lives in ./contract.ts and is re-exported by ./api.ts.
 * Phase 7: flip ./api.ts to re-export from here and reconcile any drift.
 */
export {};
